Add configuration for verification-store in base_stencil
IMGIITRoorkee/omniport-backend pull request #118
Opened 2020-09-02 14:00 UTC by kmrinal19

2020-09-02 14:13 UTC, ayushjn20 approved these changes

2020-09-07 15:13 UTC, rish9101 commented
Nice catch! 👍

2020-09-07 22:21 UTC, nisarg73 commented
@kmrinal19 Please add `emails` as well in this, and update the PR. You may refer to https://github.com/IMGIITRoorkee/omniport-docs/commit/45df2ce19c54c29dd4c14b8b747ab53d740c4061 for this.

2020-09-08 04:10 UTC, algomaster99 commented
@kmrinal19 I agree with @nisarg73 , please add the missing configurations in this PR itself.

2020-09-08 06:54 UTC, algomaster99 requested changes
Few small changes and we're good to go :smile:

2020-09-08 06:54 UTC, algomaster99 commented on configuration/base_stencil.yml
> +  emailPort: # The port used by smtp server
`smtp` -> `SMTP`

2020-09-08 06:54 UTC, algomaster99 commented on configuration/base_stencil.yml
> +  emailUseTls: # Whether an email uses a TLS connection or not
Whether an email should be encrypted via TLS or not

2020-09-08 09:14 UTC, algomaster99 approved these changes
@kmrinal19 nice work 😌

2020-09-08 09:20 UTC, merged