Fixed Updating of Created on of Developer Service on refresh
IMGIITRoorkee/omniport-backend pull request #122
Opened 2020-09-09 18:08 UTC by ruddi10

I have done a minor change in the ApplicationDetailSerializer , removed datetime_created field from exclude and added to read_only_fields

2020-09-09 18:43 UTC, algomaster99 requested changes
@ruddi10 nice work
Refer to the instructions in your other PR on how to write commit messages. Otherwise look at previous commits in this repository.

2020-09-09 18:43 UTC, algomaster99 commented on omniport/core/open_auth/serializers/application.py
> +             'datetime_created'
Remove the extra space

2020-09-10 00:32 UTC, ruddi10 commented
Made the changes you asked for.Thanks

2020-09-10 18:41 UTC, algomaster99 requested changes
last change 😅

2020-09-10 18:41 UTC, algomaster99 commented on omniport/core/open_auth/serializers/application.py
> +            'datetime_created'
Add a trailing comma

2020-09-11 06:12 UTC, ruddi10 commented on omniport/core/open_auth/serializers/application.py
> +            'datetime_created'
Done kindly review

2020-09-11 07:19 UTC, merged