Add permissions for omnipotence rights, Add static folder for new pac…
IMGIITRoorkee/omniport-backend pull request #139
Opened 2020-12-07 11:39 UTC by gauransh7

- Add permissions for omnipotence rights

- Add static folder for new package(pure-react-carousel)

2020-12-07 19:05 UTC, dhruvkb requested changes
Why does this PR contain JS files for a carousel?

2020-12-12 09:36 UTC, gauransh7 commented
> Why does this PR contain JS files for a carousel?

These files came along with a package(pure-react-carousel). Only one of the four files was of use, so I have made a commit to remove the needless files.

2020-12-13 05:57 UTC, dhruvkb commented
Even if it's useful, two separate unrelated features should belong in two separate PRs.

2020-12-13 11:51 UTC, gauransh7 commented
> Even if it's useful, two separate unrelated features should belong in two separate PRs.

Yes Sure.
Made a different PR for package changes.
Ref.- [https://github.com/IMGIITRoorkee/omniport-backend/pull/140](https://github.com/IMGIITRoorkee/omniport-backend/pull/140)

2020-12-18 17:35 UTC, pradumangoyal commented on omniport/core/kernel/permissions/omnipotence.py
This line is not needed

2020-12-20 17:54 UTC, gauransh7 commented on omniport/core/kernel/permissions/omnipotence.py
yes sure.

2020-12-25 13:36 UTC, merged